version: '3.8'

services:
  # Frontend service - development mode
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - wiss-network

  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: 
      - ./backend/.env
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/wiss_forum
      - SPRING_WEB_CORS_ALLOWED_ORIGINS=http://localhost:3000
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - wiss-network

  # MongoDB service
  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - wiss-network

networks:
  wiss-network:
    driver: bridge

volumes:
  mongodb_data: 